# list all actu
actualites:
    path:     /example/show
    defaults: { _controller: AppBundle:Actualite:exampleShow }
    methods:  GET

actualite_index:
    path:     /
    defaults: { _controller: "AppBundle:Actualite:index" }
    methods:  GET

actualite_list:
    path:     /list/
    defaults: { _controller: "AppBundle:Actualite:list" }
    methods:  GET

actualite_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Actualite:show" }
    methods:  GET