
index:
    path:     /
    defaults: { _controller: AppBundle:FrontController:index }

actualites:
    path:     /actualites
    defaults: { _controller: AppBundle:FrontController:actu }

article:
    resource: "@AppBundle/Resources/config/article/article.yml"
    prefix:     /article
