
app_index:
    path:     /
    defaults: { _controller: AppBundle:FrontController:index }

actualites:
    resource: "@AppBundle/Resources/config/routing/actu.yml"
    prefix:     /actualite

contact:
    resource: "@AppBundle/Resources/config/routing/contact.yml"
    prefix:     /contact